#!/usr/bin/env ansible-playbook
- hosts: localhost
  tasks:
    - name: hyde
      ansible.builtin.file:
        src: "{{ playbook_dir }}/hyde"
        dest: "{{ ansible_user_dir }}/.config/hyde"
        state: link

    - name:
